baseURL: https://blog.de-souza.eu
title: Léo’s Blog
languageCode: en-gb
rssLimit: 10
theme: hugo-flex
copyright: Copyright © 2019 Léo De Souza – Except where otherwise noted,
  content on this site is licensed under a Creative Commons Attribution 4.0
  International License (http://creativecommons.org/licenses/by/4.0/).

params:
  color: darkslategray
  footer: Copyright © 2019 <a href="/contact/" rel="author">Léo De Souza</a> –
    Except where otherwise noted, content on this site is licensed under a
    <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.

menu:
  nav:
  - name: About
    url: /about/
    weight: 1
  - name: Archive
    url: /archive/
    weight: 2
  - name: Tags
    url: /tags/
    weight: 3
  - name: RSS
    url: /index.xml
    weight: 4

taxonomies:
  tag: tags

outputs:
  taxonomy:
  - HTML

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true